id: P002920
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5571
  title: འཇམ་དབྱངས་བློ་གསལ་དབང་པོའི་རྣམ་པར་ཐར་པ་སྐལ་བཟང་རྣ་བའི་དགའ་སྟོན།
  author: ''
  volumes:
    d4e0929abd1647c5a21a02ac2f0c61f1:
      image_group_id: I3CN5573
      title: ''
      volume_number: 1
      total_pages: 464
