id: ID167AFDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:29:51+00:00'
last_modified: '2022-06-07T16:12:19.152442+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5571
  title: འཇམ་དབྱངས་བློ་གསལ་དབང་པོའི་རྣམ་པར་ཐར་པ་སྐལ་བཟང་རྣ་བའི་དགའ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0AF8:
      image_group_id: I3CN5573
      title: ''
      total_pages: 464
      order: 1
      base_file: 0AF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
